### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [scottwillson/dawn-patrol#1]
a much better version for this

``` js
exports.deleteAll = () => db.none('delete from results');
```

would be:

``` js
exports.deleteAll = () => db.none('truncate table results');
```

**Comment by scottwillson** [comment]
Hey, @vitaly-t thanks so much for the advice, and thanks for your work on pg-promise.

I tested `truncate` vs. `delete`, and here `delete` is faster. (If there is any difference at all). There is rarely more than 1-3 rows in the table.

That is my experience with other DBs: sometimes truncate is faster, sometimes not. But I am no Postgres expert!

**Comment by vitaly-t** [comment]
http://stackoverflow.com/questions/139630/whats-the-difference-between-truncate-and-delete-in-sql

You are welcome!
